# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://strongdan.com
title: Daniel Strong  
email: daniel@strongdan.com
author: Daniel Strong
description: > A portfolio site for Daniel Strong. 
  You can edit this line in _config.yml. It will appear in your document 
  head meta (for Google search results) and in your feed.xml site 
  description."

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: twitter
    url: https://twitter.com/danstrong
  - title: github
    url: https://github.com/strongdan
  - title: linkedin
    url: https://www.linkedin.com/pub/dan-strong/7/6a3/7a
